# Generated by Django 4.2.5 on 2025-10-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='applied_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
