# Generated by Django 4.2.5 on 2025-10-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotioncode_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncode',
            name='code',
            field=models.CharField(unique=True),
        ),
    ]
