# Generated by Django 4.2.5 on 2025-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='quantity_gte_0',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='quantity_gt_0'),
        ),
    ]
