# Generated by Django 4.2.5 on 2025-10-01 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkouts.purchasehistory')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('user_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('address2', models.CharField(blank=True, null=True)),
                ('country', models.CharField(choices=[('', '選択してください'), ('Japan', '日本')])),
                ('state', models.CharField(choices=[('', '選択してください'), ('Tokyo', '東京')])),
                ('zip', models.CharField(validators=[django.core.validators.RegexValidator('\\d{7}')])),
                ('name_on_card', models.CharField()),
                ('credit_card_number', models.CharField(validators=[django.core.validators.RegexValidator('\\d{14}')])),
                ('expiration', models.DateField()),
                ('cvv', models.CharField(validators=[django.core.validators.RegexValidator('\\d{3}')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkouts.purchasehistory')),
            ],
        ),
    ]
