# Generated by Django 4.2.5 on 2025-10-02 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='credit_card_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('\\d{14}')]),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\d{3}')]),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zip',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('\\d{7}')]),
        ),
    ]
