# Generated by Django 4.2.5 on 2025-10-03 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_alter_billingaddress_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='credit_card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('\\d{16}')]),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='expiration',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('\\d{2}/\\d{2}')]),
        ),
    ]
