# Generated by Django 4.2.5 on 2025-10-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_alter_billingaddress_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='purchased_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkouts.purchasehistory'),
        ),
    ]
