# Generated by Django 4.2.5 on 2025-10-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotioncode_code'),
        ('checkouts', '0004_alter_billingaddress_purchased_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='promotion_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotioncode'),
        ),
    ]
